### ISSUE TITLE
Questions about data sets?

### ISSUE THREAD

**Issue by linzhi123** [PetarV-/DGI#1]
Hello, how do you make the data set under the data folder?

**Comment by PetarV-** [comment]
Hello,

I'm not sure I understand your question. We use standard benchmark datasets for all experiments reported in our paper. For example, Cora, Citeseer and Pubmed can all be found in Thomas Kipf's GCN repository:
https://github.com/tkipf/gcn/tree/master/gcn/data

Thanks,
Petar

**Comment by linzhi123** [comment]
Thanks

**Comment by linzhi123** [comment]
I mean how are the files in these datasets made?
@PetarV-

**Comment by PetarV-** [comment]
Perhaps this description can help?
https://github.com/kimiyoung/planetoid/blob/master/README.md

I'm sorry I cannot be of much more help than that---I didn't take part in preparing the files.

**Comment by linzhi123** [comment]
Ok, thank you for your answer.

**Comment by svjan5** [comment]
Hi Petar,
Can you provide Reddit and PPI datasets in the format used in the code? 

Thanks

**Comment by PetarV-** [comment]
Hello,

For PPI, the preprocessing code found in:

https://github.com/PetarV-/GAT/blob/master/utils/process_ppi.py

should be enough to get you started.

For Reddit, we were unable to get the PyTorch version of GraphSAGE to cooperate, and thus we used the TensorFlow version:

https://github.com/williamleif/GraphSAGE

as a starting point, and modified it to support DGI and load Reddit. Currently there are no plans to release this modified codebase.

Thanks,
Petar

**Comment by svjan5** [comment]
Thanks a lot!
