### ISSUE TITLE
About the meaning of learned features

### ISSUE THREAD

**Issue by Fujiaoji** [PetarV-/DGI#17]
Hi, I was wondering that the learned representations tend to conserve their unique information or common information. Maximizing Mutual information between patch and summary vector is to find more information between them, but the discriminator wants to distinguish the samples. So, I am confused.

**Comment by PetarV-** [comment]
Hi Fujiao,

Thanks for your issue!
I think the key part here is that the discriminator distinguishes patches in the **original** from ones in a **corrupted** graph.
Pushing those apart will have as a consequence (see the Theorems proven in our work) a likely maximisation of mutual information within the vertices of the original graph.

Hope that helps!

Thanks,
Petar

**Comment by Fujiaoji** [comment]
> Hi Fujiao,
> 
> Thanks for your issue!
> I think the key part here is that the discriminator distinguishes patches in the **original** from ones in a **corrupted** graph.
> Pushing those apart will have as a consequence (see the Theorems proven in our work) a likely maximisation of mutual information within the vertices of the original graph.
> 
> Hope that helps!
> 
> Thanks,
> Petar

Thanks for your help! :)
Best regards,
Fujiao Ji
