### ISSUE TITLE
sigmoid function is missing in layers/discriminator.py

### ISSUE THREAD

**Issue by liangxun** [PetarV-/DGI#6]
It seems that the sigmoid function is missing in layers/discriminator.py[line30]. 
Explained in your paper, the logistic sigmoid nonlinearity is used to convert scores into probabilities of (h_i, s) being a positive example.

**Comment by PetarV-** [comment]
Hello,

Thanks for your issue. The sigmoidal function is (implicitly) applied by the `BCEWithLogitsLoss` as used here:
https://github.com/PetarV-/DGI/blob/master/execute.py#L60

Working with raw inputs allows for some numerical tricks to make the computation more stable.

Thanks,
Petar
